<?php
require_once __DIR__ . '/config.php';

// declare(strict_types=1);

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}


$userName =
    $_SESSION['user_name']
    ?? $_SESSION['fullName']
    // ?? $_SESSION['name'
    ?? 'Farmer';

$userName = htmlspecialchars(
    (string)$userName,
    ENT_QUOTES,
    'UTF-8'
);

/*
 * CSRF token for requests to your PHP AI endpoint.
 */
if (empty($_SESSION['ai_csrf_token'])) {
    $_SESSION['ai_csrf_token'] = bin2hex(random_bytes(32));
}

$csrfToken = htmlspecialchars(
    $_SESSION['ai_csrf_token'],
    ENT_QUOTES,
    'UTF-8'
);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="AI-powered farming assistance for farmers, crops, soil, pests, diseases, irrigation, weather and agricultural planning."  >

    <title>AI Farming Assistant</title>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    <link rel="stylesheet" href="../Assets/ai.css">
</head>

<body>

<div class="ai-app">

    <!-- =====================================================
         SIDEBAR
    ====================================================== -->

    <aside class="ai-sidebar" id="aiSidebar">
        <div class="sidebar-header">
            <div class="ai-logo">
                <div class="ai-logo-icon">
                    <i class="fa-solid fa-seedling"></i>
                </div>

                <div>
                    <strong>Agro AI</strong>
                    <span>Farming Assistant</span>
                </div>
            </div>

            <button
                type="button"
                class="icon-button sidebar-close"
                id="closeSidebar"
                aria-label="Close sidebar">
                <i class="fa-solid fa-xmark"></i>
            </button>

        </div>

        <button
            type="button"
            class="new-chat-button"
            id="newChatButton">
            <i class="fa-solid fa-plus"></i>
            <span>New conversation</span>
        </button>

        <div class="sidebar-section">

            <div class="sidebar-title">
                Recent conversations
            </div>

            <div
                class="conversation-list"
                id="conversationList">
                <!-- Conversations are generated by JavaScript -->
            </div>

        </div>

        <div class="sidebar-section topic-section">

            <div class="sidebar-title">
                Farming topics
            </div>

            <button
                type="button"
                class="topic-button"
                data-prompt="How can I improve the soil fertility of my farm?">
                <i class="fa-solid fa-mountain"></i>
                Soil management
            </button>

            <button
                type="button"
                class="topic-button"
                data-prompt="How can I identify and control common crop pests?"
                <i class="fa-solid fa-bug"></i>
                Pest control
            </button>

            <button
                type="button"
                class="topic-button"
                data-prompt="How do I identify crop diseases and manage them safely?" >
                <i class="fa-solid fa-leaf"></i>
                Crop diseases
            </button>

            <button
                type="button"
                class="topic-button"
                data-prompt="How should I plan irrigation for my crops?">
                <i class="fa-solid fa-droplet"></i>
                Irrigation
            </button>

            <button
                type="button"
                class="topic-button"
                data-prompt="What fertilizer should I use and how should I apply it?"
            >
                <i class="fa-solid fa-flask"></i>
                Fertilizers
            </button>

            <button
                type="button"
                class="topic-button"
                data-prompt="How can I improve my crop yield and farm profitability?"
            >
                <i class="fa-solid fa-chart-line"></i>
                Yield improvement
            </button>

        </div>

        <div class="sidebar-footer">

            <div class="farmer-mini-profile">

                <div class="farmer-avatar">
                    <?= strtoupper(substr($userName, 0, 1)) ?>
                </div>

                <div class="farmer-info">
                    <strong><?= $userName ?></strong>
                    <span>Farmer</span>
                </div>

            </div>

        </div>

    </aside>


    <!-- =====================================================
         MAIN AREA
    ====================================================== -->

    <main class="ai-main">

        <!-- HEADER -->

        <header class="ai-header">

            <button
                type="button"
                class="icon-button mobile-menu-button"
                id="openSidebar"
                aria-label="Open sidebar"
            >
                <i class="fa-solid fa-bars"></i>
            </button>

            <div class="header-title">

                <div class="online-indicator"></div>

                <div>
                    <h1>AI Farming Assistant</h1>
                    <p>
                        Intelligent agricultural guidance
                    </p>
                </div>

            </div>

            <div class="header-actions">

                <button
                    type="button"
                    class="icon-button"
                    id="clearChatButton"
                    title="Clear conversation"
                >
                    <i class="fa-solid fa-trash"></i>
                </button>

                <button
                    type="button"
                    class="icon-button"
                    id="themeButton"
                    title="Change theme"
                >
                    <i class="fa-solid fa-moon"></i>
                </button>

            </div>

        </header>


        <!-- =================================================
             CHAT
        ================================================== -->

        <section class="chat-container">

            <div
                class="chat-messages"
                id="chatMessages"
                aria-live="polite"
            >

                <!-- Welcome message -->

                <div class="welcome-screen" id="welcomeScreen">

                    <div class="welcome-icon">
                        <i class="fa-solid fa-seedling"></i>
                    </div>

                    <h2>
                        Hello, <?= $userName ?> 👋
                    </h2>

                    <p>
                        I am your AI farming assistant. Ask me
                        about crops, soil, pests, diseases,
                        irrigation, fertilizers, weather,
                        livestock, farm management and more.
                    </p>

                    <div class="suggestion-grid">

                        <button
                            type="button"
                            class="suggestion-card"
                            data-prompt="What crops grow well in my region?"
                        >
                            <i class="fa-solid fa-wheat-awn"></i>
                            <span>
                                What crops should I grow?
                            </span>
                        </button>

                        <button
                            type="button"
                            class="suggestion-card"
                            data-prompt="My crops have yellow leaves. What could be causing this and what should I check first?"
                        >
                            <i class="fa-solid fa-leaf"></i>
                            <span>
                                My crops have yellow leaves
                            </span>
                        </button>

                        <button
                            type="button"
                            class="suggestion-card"
                            data-prompt="How can I increase my farm yield?"
                        >
                            <i class="fa-solid fa-arrow-trend-up"></i>
                            <span>
                                Increase my yield
                            </span>
                        </button>

                        <button
                            type="button"
                            class="suggestion-card"
                            data-prompt="How can I identify pests affecting my crops?"
                        >
                            <i class="fa-solid fa-bug"></i>
                            <span>
                                Help with crop pests
                            </span>
                        </button>

                    </div>

                </div>

            </div>


            <!-- =================================================
                 TYPING INDICATOR
            ================================================== -->

            <div
                class="typing-indicator"
                id="typingIndicator"
                hidden
            >

                <div class="ai-avatar small">
                    <i class="fa-solid fa-seedling"></i>
                </div>

                <div class="typing-content">

                    <span>Agro AI is thinking</span>

                    <div class="typing-dots">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>

                </div>

            </div>


            <!-- =================================================
                 INPUT
            ================================================== -->

            <div class="chat-input-area">

                <div class="input-wrapper">

                    <button
                        type="button"
                        class="input-icon"
                        id="voiceButton"
                        title="Voice input"
                    >
                        <i class="fa-solid fa-microphone"></i>
                    </button>

                    <textarea
                        id="messageInput"
                        rows="1"
                        maxlength="4000"
                        placeholder="Ask your farming question..."
                        aria-label="Ask your farming question"
                    ></textarea>

                    <div class="input-actions">

                        <span
                            class="character-count"
                            id="characterCount"
                        >
                            0 / 4000
                        </span>

                        <button
                            type="button"
                            class="send-button"
                            id="sendButton"
                            title="Send message"
                        >
                            <i class="fa-solid fa-paper-plane"></i>
                        </button>

                    </div>

                </div>

                <p class="input-disclaimer">
                    AI advice should be verified with local
                    agricultural experts when decisions could
                    affect crops, livestock, finances or safety.
                </p>

            </div>

        </section>

    </main>

</div>


<!-- =========================================================
     CONFIGURATION FOR JAVASCRIPT
========================================================== -->

<script>
window.AgroAIConfig = {
    csrfToken: <?= json_encode($csrfToken) ?>,

    /*
     * Replace this URL with the PHP file that communicates
     * with your AI provider.
     */
    endpoint: "ai-assistant.php",

    userName: <?= json_encode($userName) ?>,

    maxMessageLength: 4000
};
</script>

<script src="../scripts/ai.js"></script>

</body>
</html>